Add endpoints for ticket validation and attendant creation
EventAccess/BackendAPI pull request #22
Opened 2024-11-29 21:01 UTC by HollowKaeden

Implement issues #15 and #16

2024-11-29 21:05 UTC, HollowKaeden commented on .gitignore
Created a virtual environment and added it to .gitignore to prevent unnecessary files from being tracked

2024-12-02 17:02 UTC, oddstr13 requested changes

2024-12-02 17:02 UTC, oddstr13 commented on .gitignore
> +venv
```suggestion
venv

```

2024-12-02 17:02 UTC, oddstr13 commented on backendapi/urls.py
> +    path("attendants/", views.create_attendant, name="create_attendant")
```suggestion
    path("test", views.api_get, name="api_get"),
    path("tickets/verify/<slug:ticket>",
         views.verify_ticket,
         name="verify_ticket"),
    path("attendants", views.create_attendant, name="create_attendant")
```

no trialing slash on API paths

2024-12-02 17:02 UTC, oddstr13 commented on backendapi/views.py
> +            }
```suggestion
            "id": attendant.id,
```

`id` is the only field that would be unknown to the client, and `discord`, `is_crew` and `is_valid` will never have anything but the default values.

We can add a return of the whole object if we find that we need it later, but then we should probably use a generator

2024-12-03 14:28 UTC, oddstr13 approved these changes

2024-12-03 14:28 UTC, merged